### ISSUE TITLE
Please, add event

### ISSUE THREAD

**Issue by ghost** [smietanka/CocNET#2]
Please, add event 'Maintenance'
field: 'reason','message'
is bool wanted, return true/false and method get message about Maintenance period.

**Comment by smietanka** [comment]
Thanks for the issue, today I will add this feature :)

**Comment by ghost** [comment]
Good!

**Comment by ghost** [comment]
Great interest is the treatment of the information on this API link:
https://api.clashofclans.com/v1/clans/[clan tag]/warlog

**Comment by smietanka** [comment]
Already added. Sry for long wainting.
